application: cornell-ol
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin
  
- url: /.*
  script: main.app
#  secure: always

inbound_services:
- mail

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "2.5.2"